openapi: 3.1.0
info:
  title: Pact Backend API - Health Check
  description: Health check endpoint for backend API deployment verification
  version: 1.0.0
  contact:
    name: Pact API Support

servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://api.pact.app
    description: Production server (Railway)

paths:
  /health:
    get:
      summary: Health Check
      description: |
        Verifies that the backend API is running and can connect to the database.
        Used by deployment platforms (Railway) and load balancers for health monitoring.

        Returns 200 OK when both application and database are healthy.
        Returns 503 Service Unavailable when database is unreachable.
      operationId: getHealth
      tags:
        - Health
      responses:
        "200":
          description: System is healthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
              examples:
                healthy:
                  summary: Healthy system
                  value:
                    status: ok
                    timestamp: "2026-01-04T12:00:00.000Z"
                    database: connected
        "503":
          description: Service unavailable (database connection failed)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                databaseDown:
                  summary: Database unreachable
                  value:
                    statusCode: 503
                    message: Database connection failed
                    timestamp: "2026-01-04T12:00:00.000Z"
                    path: /health

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          enum: [ok]
          description: Overall health status
          example: ok
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp of health check
          example: "2026-01-04T12:00:00.000Z"
        database:
          type: string
          enum: [connected, disconnected]
          description: Database connection status (optional, included when checked)
          example: connected

    ErrorResponse:
      type: object
      required:
        - statusCode
        - message
        - timestamp
        - path
      properties:
        statusCode:
          type: integer
          description: HTTP status code
          example: 503
        message:
          type: string
          description: Error message
          example: Database connection failed
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp of error
          example: "2026-01-04T12:00:00.000Z"
        path:
          type: string
          description: Request path that caused the error
          example: /health

tags:
  - name: Health
    description: System health monitoring endpoints
